# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"
  - name: "RegexFeaturizer"
  - name: "SpacyEntityExtractor"
    features: [
              ["low", "title", "upper"],
              ["bias", "low", "prefix5", "prefix2", "suffix5", "suffix3",
               "suffix2", "upper", "title", "digit", "pattern"],
              ["low", "title", "upper"]
            ]
  #- name: "nlp_spacy"
  #- name: "tokenizer_spacy"
  #- name: "intent_entity_featurizer_regex"
  #- name: "intent_featurizer_spacy"
  #- name: "ner_spacy"
  #- name: "ner_crf"
  #- name: "ner_synonyms"
  #- name: "intent_classifier_sklearn"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  
